FROM python:3.12

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./docker/cons_entrypoint.sh /cons_entrypoint.sh
RUN sed -i 's/\r$//g' /cons_entrypoint.sh
RUN chmod +x /cons_entrypoint.sh

COPY . .

ENTRYPOINT ["/cons_entrypoint.sh"]